#!/usr/bin/env bash
# Install and configure load balancer

load_balance_config="\
frontend welcomeClient
        bind *:80
        mode http
        default_backend twoWebServers

backend twoWebServers
        balance roundrobin
        server 336952-web-01 100.25.0.134
        server 336952-web-02 52.86.81.94
"

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy
echo "$load_balance_config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
