#!/usr/bin/env bash
# Install and configure load balancer

load_balance_config="\

frontend welcomeClient
        bind *:80
        mode http
        default_backend twoWebServers

backend twoWebServers
        balance roundrobin
        server 336952-web-01 100.25.0.134 check
        server 336952-web-02 52.86.81.94 check

"

sudo apt-get -y update

# Add HAProxy PPA
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8


# install HAProxy
sudo apt-get -y install haproxy=2.8.\*

# backup and configure haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$load_balance_config" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
